---
  - name: add google key to apt
    apt_key:
      url=https://dl-ssl.google.com/linux/linux_signing_key.pub

  - name: add debian package to sources list
    lineinfile:
      dest=/etc/apt/sources.list.d/google.list
      line='deb http://dl.google.com/linux/chrome/deb/ stable main'
      state=present
      create=yes
    register: added_debian_package
    
  - name: update
    apt:
      upgrade=dist

  - name: fix packages
    shell: apt-get -qq -f install
    when: added_debian_package.changed

  - name: install google chrome
    apt:
      name=google-chrome-stable
      state=present

  - name: udpate chrome shortcut command
    replace:
      dest=/usr/share/applications/google-chrome.desktop
      regexp='^(.*google-chrome-stable.*)$'
      replace='\1 --disable-gpu'
