---
  - name: install packages
    apt:
      name=ubuntu-desktop
      state=present
      install_recommends=no

  - name: install packages
    apt:
      name={{ item }}
      state=present
    with_items:
      - unity-lens-*
      - unity-scope-home
      - graphviz
      - zram-config
      - sslscan
